spring.application.name=task-api

# Banco de dados H2
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Console do H2 (interface visual do banco no browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console